### ISSUE TITLE
Ability to select elements in invalid HTML locations

### ISSUE THREAD

**Issue by cdloh** [cloudflare/lol-html#106]
I noted the recent addition of some of the ESI tags to the rewriter and thought about giving it a look to see if it could replace our current ESI parser.

However I noted that I wasn't able to select elements that were in places they really shouldn't be.

Here is an example of some HTML that has some ESI in it that I've seen used.

```
<li class="<esi:choose><esi:when test="$(ESI_ARGS{frontend_asset_lineage}) =~ '/,2757,/i'">active</esi:when></esi:choose>">

<div class="smp-subnav__title <esi:choose><esi:when test="$(ESI_ARGS{frontend_asset_lineage}) =~ '/,2757,/i'">active</esi:when></esi:choose>"> 	
```

This adds a class to a div or li based on some other ESI args being passed to it. An odd method of going about it but just one example.

Would there be any motivation here to make changes to the project to be able to support elements that are in places that aren't valid HTML so that they could be selected? 

Edit: I understand this is invalid HTML and breaks many many specs however thought it'd be worth asking!

**Comment by inikulin** [comment]
The project doesn't aim to support custom formats.
