### ISSUE TITLE
Detecting void elements

### ISSUE THREAD

**Issue by mwcz** [cloudflare/lol-html#160]
Thanks for lol-html; it's delightful!

I'm in a situation where I need to detect self-closing tags, including [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements).  `Element::is_self_closing` detects explicit self-closing tags (`<foo />`), but not void elements, which are implicitly self-closing (`<img>`).  AFAICT, whether an element is void is known by stack.rs, but is later mixed into `element.can_have_content` and the exact voidness value is lost.

Would any of the following options be palatable?

 1. Change `Element::is_self_closing` to return `true` for explicit self-closing tags _and_ void elements (ie, have it return `!self.can_have_content` instead of `self.start_tag.self_closing()`).
 2. Add a new function, like `Element::is_void` which bubbles up the result of stack.rs's `is_void_element`.  This seems like it would require the most code changes.
 3. Add a new function, like `Element::can_have_content` which returns `self.can_have_content`.  One or the other can be renamed to avoid the name collision.
 4. Some other option? :thinking: 

Any one of these would be enough to do what I'm hoping to do, and I'm happy to put together a PR after a tip on what the best approach is.  Thanks!

**Comment by Jared-Sprague** [comment]
Yes we really need this!  Would love to see this fixed.

**Comment by mwcz** [comment]
I added a draft PR the patch we're using in the meantime.

**Comment by orium** [comment]
Closed by #163.
