### ISSUE TITLE
Confusion around `el.can_have_content()`

### ISSUE THREAD

**Issue by bru02** [cloudflare/lol-html#189]
Take the following code snippet:
```rust
use lol_html::{element, HtmlRewriter, Settings};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut output = vec![];

    let mut rewriter = HtmlRewriter::new(
        Settings {
            element_content_handlers: vec![
                element!("span", |el| {
                    println!("{}", el.can_have_content());
                    el.set_inner_content("Content", lol_html::html_content::ContentType::Text);

                    Ok(())
                })
            ],
            ..Settings::default()
        },
        |c: &[u8]| output.extend_from_slice(c)
    );

    rewriter.write(b"<span/>")?;
    rewriter.end()?;
    print!("{}", String::from_utf8(output).unwrap());
    Ok(())
}
```

According to [`el.can_have_content()` docs](https://docs.rs/lol_html/latest/lol_html/html_content/struct.Element.html#method.can_have_content), I would expect a self-closing tag to not be able to have content, but my script outputs `true`.

Okay, so what happens when i set some content?

I get: `<span/>Content`.

Huh. If the span can have content, I would expect `<span>Content` or `<span>Content</span>`.

I'm not sure if I'm misinterpreting the docs or if I stumbled upon a bug.

**Comment by mwcz** [comment]
I think lol-html is correct, here.  HTML (5, at least) doesn't have self-closing tags.  `<span/>` isn't a self-closing span, it's an opening span with a `/` that gets ignored.  In devtools, try adding `<span/>` to the middle of some text and see how the browser interprets it.

HTML5 only allows for self-closing tags in embedded foreign content (SVGs, MathML, etc).  Void elements are the HTML5 version of self-closing tags, being tags with no closing tag such as `meta` and `base`.  They don't require a `/` though if one is present it will be ignored.  `<meta> == `<meta/>`
