### ISSUE TITLE
rewriter.end() self is non reference

### ISSUE THREAD

**Issue by luwes** [cloudflare/lol-html#204]
https://github.com/cloudflare/lol-html/blob/44a7659d1ce018c27ae1f7e7913884bdedf72d71/src/rewriter/mod.rs#L251-L251

I'm just starting out learning Rust so this might be intended but should the self param not be a reference?

```rs
    #[inline]
    pub fn end(mut self) -> Result<(), RewritingError> {
        guarded!(self, self.stream.end())
    }
```

should `mut self` be `&mut self` ?

I bring this up because I had a problem saving the rewriter in a struct field, the compiler complained it couldn't move or dereference...

**Comment by trevyn** [comment]
It’s a common Rust idiom for a “finalizer” method to take ownership of self, to ensure that nothing else can be called on a finished object.

Putting it in a struct feels a bit anti-pattern to me, but if you really want to, you can put an Option<T> in your struct and then do .take() to call the finalizer.

**Comment by luwes** [comment]
thanks for the quick answer! makes sense. 
I'll see if I can re-organize it without adding it to a struct.
