### ISSUE TITLE
Depends on deprecated and to-be-removed rustc-serialize feature

### ISSUE THREAD

**Issue by RalfJung** [cloudflare/lol-html#251]
The old rustc-serialize infrastructure is deprecated and will potentially be removed from the compiler (see https://github.com/rust-lang/rust/issues/134301). This repo has a [dependency](https://github.com/cloudflare/lol-html/blob/33ab3b8b431ac5630edbf221dec551b7033fbccc/Cargo.toml#L58) on rustc-test which seems unmaintained (no release in 4 years) and which uses this deprecated infrastructure. You should already be seeing warnings that this will break in a future version of rustc, and if https://github.com/rust-lang/rust/pull/134272 is merged into the compiler, that future version will come soon. So please let us know if there's any trouble with migrating away from the old  rustc-serialize feature.

**Comment by kornelski** [comment]
We use it to auto-generate 344950 integration tests. 

I've seen the warnings, but AFAIK there's no replacement, and no chance of Cargo getting a proper testing framework anytime soon, so I'm planning to keep using the bad dependency until it completely breaks.

**Comment by RalfJung** [comment]
rustc-test has hardly any users. In a crater run, this repo is literally the only one on all of crates.io that broke due to rustc-test. So it's not clear what kind of a replacement you are looking for, but clearly the rest of the ecosystem is doing fine without rustc-test. (Looking at reverse dependencies, I noticed there's also markup5ever_rcdom, also maintained by you, but that has been migrated away recently in https://github.com/servo/html5ever/pull/528.)

The regular "test" crate has loooong been ported away from the old rustc-serialize infrastructure. It would likely not be too hard to also do that with this unmaintained fork. Do you even need the JSON functionality?

But as usual when you pick up a dependency, if they become unmaintained you have to figure out a solution. I'd be happy to wait a bit with landing that rustc change to give this crate a chance to migrate, but there's no point in that if you don't plan to do anything until you are forced to. :shrug:

**Comment by RalfJung** [comment]
Would you accept a patch similar to https://github.com/servo/html5ever/pull/528 ?

**Comment by kornelski** [comment]
The servo change doesn't look as bad as I feared. I'll give it a try.

**Comment by RalfJung** [comment]
Thanks a lot :)
