### ISSUE TITLE
:nth-child

### ISSUE THREAD

**Issue by BraunreutherA** [cloudflare/lol-html#44]
Hi there, 

we're trying to generate css selectors automatically and use them with HTMLRewriter (on Cloudflare workers) / lol-html. 
For a guaranteed selector generation we need to use :nth-child selectors in some cases. I completely understand that this could be impossible due to the streaming nature of lol-html. 
Did you approach (and maybe have a workaround) for such a case?

Thanks and all the best

Alex

**Comment by inikulin** [comment]
Hi Alex,

It's possible to implement `nth-child` selector in streaming parser. Though, we decided to not implement it initially as it will significantly complicate the selectors VM. But, since there is a demand for this, we might consider doing that.  

For now, the only workaround that comes to my mind is to specify a selector for children (e.g. `#parent > li`) and manually count n-th element in your code.

**Comment by BraunreutherA** [comment]
Hi @inikulin, 

that sounds great! Please let me know if you decide to implement it. 

So you mean we should catch a selector, parse it e.x. `#parent > li:nth-child(3)` and set it in a piece of code like this: 

```ts
class NthChildRewriter {
  childIndex: number;
  index: number;

  constructor(childIndex: number) {
    this.childIndex = childIndex;
    this.index = 1;
  }

  // TODO need to find typings for HTMLRewriter
  element(element) {
    if (this.index === this.childIndex) {
      element.setAttribute('this was our child!');
    }

    this.index++;
  }
}

new HTMLRewriter.on('#parent > li', new NthChildRewriter(3)).transform(htmlResponse);
```

This could work, but would get very complicated especially for nested child selectors e.x. `#parent > div:nth-child(2) > li:nth-child(3)`. This way we would need multiple loops inside of each other - don't know if it would work.

**Comment by BraunreutherA** [comment]
Thanks for the tip with counting the elements in my code! Here is a workaround (probably not the most performant way but it works):

```ts
const sanitizeSelector = (selector: string) => {
  const nthChildRegex = /:nth-child\(\d+\)/g;
  const digitRegex = /\d+/;

  const matches = selector.match(nthChildRegex)

  if (matches) {
    const index = matches.map(nthChild => nthChild.match(digitRegex))
      .flat()
      .map(digit => parseInt(digit))
      .reduce((prev, curr) => prev * curr);

     const simplifiedSelector = selector.replace(nthChildRegex, '');
     return { index, selector: simplifiedSelector };
  }
  
  return {index: 1, selector};
}

class NthChildRewriter {
  childIndex: number;
  index: number;

  constructor(childIndex: number) {
    this.childIndex = childIndex;
    this.index = 1;
  }

  // TODO need to find typings for HTMLRewriter
  element(element) {
    if (this.index === this.childIndex) {
      element.setAttribute('this was our child!');
    }

    this.index++;
  }
}

const selector = '#parent > li:nth-child(3) > div:nth-child(2)

new HTMLRewriter.on('#parent > li', new NthChildRewriter(3)).transform(htmlResponse);
```

This works also with nested nth-child selectors as the indices of the inner loops can be safely multiplied as the parser runs through the elements by depth. 

Hope this helps some others - maybe it's still possible to add the native feature.

**Comment by inikulin** [comment]
@BraunreutherA Didn't notice that you using it from Workers. It's worth opening a feature request in the [Community Portal](https://community.cloudflare.com/). So, Workers team will be aware about the feature request as well (this repo is for the HTMLRewrite back-end only).

**Comment by BraunreutherA** [comment]
@inikulin alright, thanks! I thought what gets changed here will get into the worker :)

**Comment by toinbis** [comment]
Identical requirement we are having. We also generate css selectors and need to find a way to select element based on that in Workers. @BraunreutherA thanks for raising this as well as sharing the code snippets! Could I reach out to you in case I do need some clarifications on your code?

**Comment by BraunreutherA** [comment]
@toinbis  sure - if you have questions feel free to ask!
