### ISSUE TITLE
Unable to find match using selectors with a colon in the attribute value

### ISSUE THREAD

**Issue by chlao** [cloudflare/lol-html#50]
I'm attempting to replace the a Google Fonts stylesheet URL with the contents of the stylesheet. I was using HTMLRewriter about a week ago and it was working fine, but I noticed today after I published to my worker, that it stopped working as expected even though it I had not made any changes that would have made a difference. 

So, I started testing out different selectors. This seems to work fine: 
```
rewriter.on(`link[href*="fonts.googleapis.com/css"]`, ...)
```

But, when a colon was added to the font, it wouldn't work, and the handler would not be called: 
```
rewriter.on(`link[href*=":fonts.googleapis.com/css"]`, ...)
```

I was having issues with these two cases as well. This works fine: 
```
rewriter.on(`[href*="fonts.googleapis.com/css?family"]`, ...)
```

But, this does not: 
```
rewriter.on(`[href*=fonts.googleapis.com/css?family=Lato"]`, ...)
```
It feels like the last two cases could be an issue with the equals sign.

**Comment by inikulin** [comment]
Equals sign needs to be escaped in CSS selectors. Here is the excellent read on the subject: https://mathiasbynens.be/notes/css-escapes

**Comment by chlao** [comment]
I've tried escaping with a backslash, but it isn't working. I'm not sure if I'm missing something here.  

```
rewriter.on(`[href*="\:fonts"]`, ...)
```

**Comment by chlao** [comment]
I've tried escaping it with backslashes, but I'm not sure if I'm missing something because it doesn't work. 
```
rewriter.on(`[href*="https\:\/\/fonts\.googleapis\.com\/css\?family\=Lato"]`, ...)
```

But this seems to work, right before we get to the equals sign: 
```
rewriter.on(`[href*="https\:\/\/fonts\.googleapis\.com\/css\?family", ...)
```

**Comment by inikulin** [comment]
You need to double escape `\` in selector, otherwise `\=` gets resolved to just `=` by the JS engine and rewriter receives unescaped string. Try:
```
rewriter.on(`[href*=fonts.googleapis.com/css?family\\=Lato"]`, ...)
```

**Comment by chlao** [comment]
I'm not sure why, but that doesn't seem to be working either. 
```
rewriter.on(`[href*="fonts.googleapis.com/css?family\\=Lato"]`, ...)
```

**Comment by inikulin** [comment]
Definitely works on the back end side - the following test passes for me:
```
    #[test]
    fn rewrite_html_str() {
        let res = rewrite_str(
            "<a href='fonts.googleapis.com/css?family=Lato'></a>",
            RewriteStrSettings {
                element_content_handlers: vec![element!(r#"[href*="fonts.googleapis.com/css?family\=Lato"]"#, |el| {
                    println!("Handler!!");
                    el.set_tag_name("span").unwrap();
                    Ok(())
                })],
                ..RewriteStrSettings::default()
            },
        )
        .unwrap();

        assert_eq!(
            res,
            "<span href='fonts.googleapis.com/css?family=Lato'></span>"
        );
    }
```
 @ObsidianMinor could it be some issue with the front end?

**Comment by inikulin** [comment]
@ObsidianMinor It turns out I've had an old revision and it indeed was broken in d00ab48fb1c06df7b577ebf481cfa3696d1f4b4e.

**Comment by ObsidianMinor** [comment]
Yeah, looks like I mixed up a `compile_literal_lowercase` call in `compile_operands`. Sorry about that. Writing a PR now.
