### ISSUE TITLE
Take any `Into<Settings>` for rewrite_str()

### ISSUE THREAD

**Issue by jyn514** [cloudflare/lol-html#56]
Currently, `rewrite_str` only takes a `RewriteStrSettings`, so you can't e.g. configure the memory limit like you could with the full `settings`. It's possible to use `HtmlRewriter` directly, but this is a lot more code and duplicates almost everything in `rewrite_str`. It would be better to take `settings: impl Into<Settings>` in rewrite_str(), which makes the API a lot more flexible.

**Comment by jyn514** [comment]
I'm interested in implementing this.

**Comment by inikulin** [comment]
Any PRs are appreciated.
