### ISSUE TITLE
HtmlRewriter::end() should take `self`, not `&mut self`

### ISSUE THREAD

**Issue by jyn514** [cloudflare/lol-html#59]
[As documented](https://docs.rs/lol_html/0.2.0/lol_html/struct.HtmlRewriter.html#method.write), both `end()` and `write()` will panic if you do anything with the rewriter after you call `end()`. This can be enforced statically by having `end()` consume the writer.

**Comment by inikulin** [comment]
This is how it was implemented initially, but IIRC there were some problems with C API because of that. Need to check.
