### ISSUE TITLE
Support Reading of HTML without Rewriting

### ISSUE THREAD

**Issue by CoolOppo** [cloudflare/lol-html#71]
In a tool I'm writing that bundles JS, I have to make multiple passes over the HTML; it's necessary to get a list of *all* the `<script>` elements with a `src` attribute so that I can bundle them before actually doing the rewriting. This forces me to run `rewrite_str` twice, and in the first pass, I don't even modify the HTML. This is actually doing the job just fine, but I can't help but think there should be a way to use the read-only features LOL HTML has without duplicating the input HTML and then throwing out the result.

**Comment by jyn514** [comment]
`cargo deadlinks` would also like this for finding anchor tags. Maybe it could be another library on top of LOL_HTML? AFAIK lol-html is pretty efficient if you don't have any rewriters.

**Comment by inikulin** [comment]
Hi everyone, lol-html is designed the way that it doesn't allocate or duplicate the input if nothing is rewritten. Even with rewriting it doesn't re-allocate the parts of the input that are not rewritten.

**Comment by CoolOppo** [comment]
I guess that settles it!
