### ISSUE TITLE
Is this crate performant if you don't want to rewrite the HTML, just extract data?

### ISSUE THREAD

**Issue by vedantroy** [cloudflare/lol-html#79]
I'd like to use this crate for the tasks of
1. extracting all readable text from the `<body>` of an HTML document (text not inside script/style tags)
2.  Extracting all links from an HTML page

I notice the example in the README demonstrates the rewriting capabilities of this crate, however, I have no need to rewrite HTML, just extract some data. Is this crate still performant for such a task?

Hope this question makes sense.

**Comment by inikulin** [comment]
Hi,

Yes it is performant in this case and even more performant than with rewriting as it needs to do less work.

**Comment by vedantroy** [comment]
@inikulin Thanks for the response. To avoid rewriting do I just pass an empty closure as the output sink?

**Comment by inikulin** [comment]
It won't rewrite anything if you don't call any of the mutation API on the rewritable units (like `remove`, `set_tag_name`, etc.)

**Comment by inikulin** [comment]
Closing the ticket as the question was addressed. Feel free to re-open, if you have more questions.
