### ISSUE TITLE
How to get all element attributes

### ISSUE THREAD

**Issue by ewwink** [cloudflare/lol-html#81]
I tried below but it not return the attributes

```
rewriter.on(selector, {
  element(element) {
    for (var key in element.attributes) {
      console.log(key) // it print only 'next' 
    }
  }
}
```

**Comment by inikulin** [comment]
For questions about Cloudflare Worker's HTMLRewriter, please, refer to https://community.cloudflare.com/ or support. This repo is for the HTMLRewriter's back end solely.
