### ISSUE TITLE
Removing the doctype

### ISSUE THREAD

**Issue by jed** [cloudflare/lol-html#88]
I'm not sure this is possible and I'm missing it, but it would be great to be able to remove the document's doctype.

**Comment by gjtorikian** [comment]
Fancy running into you here, @jed ! 

I needed this for a project, too, and I just opened a PR for it: https://github.com/cloudflare/lol-html/pull/129

**Comment by jyn514** [comment]
This seems reasonable to me, but I'm curious why you would need to remove the doctype?

**Comment by jed** [comment]
In my case, the ability to remove the doctype means that you can stream HTML into valid JSON directly.

**Comment by jed** [comment]
Very cool. Just out of curiosity, any idea when this would land in the production runtime?

**Comment by jyn514** [comment]
@jed There is additional work on the runtime side to add this to JS; I'm not on the workers team and don't know whether they plan to add it at all.

**Comment by jed** [comment]
Awesome, thanks. Let me know if there's anywhere I should help bring it up. :bow:

**Comment by jyn514** [comment]
@evanderkoogh is involved in product on the workers side I think, he might know who to contact.
