### ISSUE TITLE
Skip SVG content in doc_text

### ISSUE THREAD

**Issue by artemyarulin** [cloudflare/lol-html#95]
Use case is getting only actual text content from the page.

Currently `document_content_handlers: vec![lol_html::doc_text!(|t| {buf += t.as_str()` will collect also `style`, `script` and other tags content. We could avoid it by filtering out by using `t.text_type() == lol_html::html_content::TextType::Data` which works for `style|script` but unfortunately `svg` tags returns also `TextType::Data` 

List of predefined tags that has different `TextType` is defined here and I wonder if `svg` could be just added there to behave more like `style` ? Or is there other better way to get text content from the page without additional non visible text?

https://github.com/cloudflare/lol-html/blob/366eb54eb857ceca3ad80efc8846e24d539a750b/src/parser/tree_builder_simulator/mod.rs#L82

**Comment by inikulin** [comment]
you can create a CSS selector that excludes style, script etc. elements and use text handler to collect the text chunks
